theme = "onedark"

[editor]
line-number = "relative"
mouse = false
true-color = true
#text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
